### ISSUE TITLE
Investigate concurrent-ruby to encapsulate threaded behavior more safely.

### ISSUE THREAD

**Issue by tpitale** [tpitale/mail_room#100]
The concurrent-ruby library appears to have reached a reasonable level of stability and is in use by a number of major ruby projects.

It may be worth investigating to see if it could be leveraged to improve the code around threaded behaviors in mail_room. It would be our only required dependency.

Areas that may be improved:

* coordinator
* mailbox_watcher
* connection (?)
* …

**Comment by tpitale** [comment]
@DouweM Would you or someone else from GitLab like to weigh in on this?

**Comment by DouweM** [comment]
@cablett Would you like to weigh in on this? :)

**Comment by cablett** [comment]
I'll take a look at this later this week or early next week. Thank you for pinging me, I'd be delighted to be part of this conversation. ✨

**Comment by tpitale** [comment]
I think my big question is: does adding this dependency make it distinctly harder for gitlab to use mail_room.

**Comment by cablett** [comment]
Thank you for the clarification - this week got away on me. Do you have a timeline for this issue?

**Comment by tpitale** [comment]
No timeline, it just dovetails with #99 and my plan to use concurrent-ruby for that. In the case of 99 it would be optional, but I think adding it to the main project might provide some good cleanup for the start of a post-1.0 release.

**Comment by tpitale** [comment]
Looks like what I really want is the `Actor` which a part of their "edge" library. Until it moves into stable, I could use `Async` and get the `async` and `await` proxies. I might give that a spike just to see if it improves the code. If not, we can hold on this until `Actor` becomes available in stable.

**Comment by tpitale** [comment]
I spiked out some changes, and while it let me maybe get rid of `Coordinator` and `MailboxWatcher`, I'm not really sure it would work. It was also much more difficult to test.

Fun experiment, but closing this for now.
