### ISSUE TITLE
Enable "Build pushed branches" in Travis CI

### ISSUE THREAD

**Issue by bjfish** [tpitale/mail_room#124]
Could you please enable "Build pushed branches" in Travis CI?
https://docs.travis-ci.com/user/web-ui/#build-pushed-branches

We would like to track build status for the `master` branch which currently does not have any builds:
https://travis-ci.org/github/tpitale/mail_room/branches

**Comment by tpitale** [comment]
What do you mean it doesn't have any builds? https://travis-ci.org/github/tpitale/mail_room/builds/137787785 That's a build of the master branch. It doesn't have any _actively_ running right now because no changes have been merged recently …? `master` is the default branch, which always builds.

**Comment by bjfish** [comment]
@tpitale The build linked to ( https://travis-ci.org/github/tpitale/mail_room/builds/137787785 )  is from 5 years ago, the most recent merge was just 6 days ago: https://github.com/tpitale/mail_room/commits/master

You can see in the commit history all of the CI statuses appear on the PR branches but none on the merge commit (in master):
https://github.com/tpitale/mail_room/commits/master

Here is one example illustrating builds on the `master` branch:
https://github.com/ruby-concurrency/concurrent-ruby/commits/master
https://travis-ci.org/github/ruby-concurrency/concurrent-ruby/builds

**Comment by tpitale** [comment]
Oh, I see it building PRs. My mistake. Strange default behavior 🤔

**Comment by tpitale** [comment]
Enabled.

<img width="528" alt="Screen Shot 2021-03-23 at 10 34 08 AM" src="https://user-images.githubusercontent.com/163/112173202-5b34c280-8bc3-11eb-8676-839e95d12307.png">
