### ISSUE TITLE
certificate verify failed

### ISSUE THREAD

**Issue by ahmadabdelhalim** [tpitale/mail_room#129]
I keep getting "certificate verify failed (OpenSSL::SSL::SSLError)" when I use the command `mail_room -c config/mailroom.yml`
and I don't understand why exactly, any help?

**Comment by tpitale** [comment]
Sounds like the certificates on the machine you're running `mail_room` on does not have them properly configured. Please look up how to configure certificates on the machine. That error is fairly common in the Ruby world.

You can also disable SSL verification, but I would advise against it. (Section about `verify_mode` in https://github.com/tpitale/mail_room#imap-server-configuration)
