### ISSUE TITLE
Request to release for OAuth2 v2.0

### ISSUE THREAD

**Issue by zach-brown-hpa** [tpitale/mail_room#162]
The commit below adds support for OAuth2 v2.0. Can we have a new release including this commit?

Some great and important updates have been merged since the last tag 0.10.1 back in 2021. Would greatly appreciate a way to use this package with the OAuth2 update!

https://github.com/tpitale/mail_room/commit/48f8e0822ef407d517671a93a05222bee17af04c

**Comment by zach-brown-hpa** [comment]
@tpitale @stanhu it seems I can do this myself by cloning the repo and running on master:
```
git tag -a v0.10.2 -m "Allow OAuth2 v2.0"
git push v0.10.2
```
Would you like me to do this? Happy to help however possible

**Comment by stanhu** [comment]
@tpitale only has permissions to push to RubyGems. 

You could always use https://rubygems.org/gems/gitlab-mail_room.

**Comment by tpitale** [comment]
I can try to release this when I get home from work.

**Comment by zach-brown-hpa** [comment]
Thanks for your replies gents. I see the latest changes are live at https://rubygems.org/gems/gitlab-mail_room. I can use that instead. Consider this closed!
