### ISSUE TITLE
Encoding issues with Faraday

### ISSUE THREAD

**Issue by tbreier** [tpitale/mail_room#21]
I am using mail_room in combination with the `postback` delivery method (hence using `Faraday`). I somehow noticed that emails containing a `%` got "lost" (they were marked as 'seen' in GMail, but the specified `delivery_url` was apparently never called).

I digged a little into it and, by enabling logging for Faraday, confirmed my suspicion that there might be an encoding issue: When an email containing a `%` (for example: An email with the message body `test %`) gets POSTed through Faraday, the message delivery silently fails: 

```
I, [2015-03-23T14:46:12.456947 #98851]  INFO -- : post https://xxxxxxx.xxxxxxx
D, [2015-03-23T14:46:12.457528 #98851] DEBUG -- request: User-Agent: "Faraday v0.9.1"
Authorization: "Token token=\"my_token\""
Content-Type: "application/x-www-form-urlencoded"
I, [2015-03-23T14:46:13.057616 #98851]  INFO -- Status: 400
D, [2015-03-23T14:46:13.057934 #98851] DEBUG -- response: transfer-encoding: "chunked"
connection: "close"
status: "400 Bad Request"
```

That kind of makes sense, because a `%` cannot stand on its own using x-www-form-urlencoded. (Try, for example http://stackoverflow.com/test%test).

I seem to be able to successfully POST an email with a `%` if I pass `URI.encode_www_form_component(message)` instead of `message` to Faraday. I am a little confused by that though, because I would have assumed that Faraday automatically handles encoding...?

**Comment by tpitale** [comment]
There may be a middleware I can add. Thanks for reporting!

**Comment by buchgr** [comment]
@tbreier nice investigation! well done!

**Comment by tpitale** [comment]
@tbreier is it your rails app that is returning the 400?

I might be able to use settings like: https://github.com/lostisland/faraday#advanced-middleware-usage

**Comment by tbreier** [comment]
Right, my app is returning the 400. The request doesn't seem to reach Rails itself though (don't see the request happening in the log files). However, there definitely might be an issue with my configuration, because using a test service like http://www.posttestserver.com/ does not have the same problem. 

See the gist below, both requests work using http://www.posttestserver.com/, but the second one returns `400 Bad Request` when I use my app. I'll investigate further..

https://gist.github.com/tbreier/ee35b59e598d44535452

**Comment by tbreier** [comment]
Okay, here is a small Rails app to demonstrate that behavior: https://github.com/tbreier/faraday_test

Just run the server `bin/rails server` and then run the script `ruby faraday_encoding.rb`.

I get the following output for the script:
```
$ ruby faraday_encoding.rb 
I, [2015-03-23T17:39:39.596767 #8274]  INFO -- : post http://localhost:3000/
D, [2015-03-23T17:39:39.596874 #8274] DEBUG -- request: User-Agent: "Faraday v0.9.1"
I, [2015-03-23T17:39:39.937822 #8274]  INFO -- Status: 200
D, [2015-03-23T17:39:39.937929 #8274] DEBUG -- response: x-frame-options: "SAMEORIGIN"
x-xss-protection: "1; mode=block"
x-content-type-options: "nosniff"
content-type: "text/html; charset=utf-8"
etag: "W/\"505a83f220c02df2f85c3810cd9ceb38\""
cache-control: "max-age=0, private, must-revalidate"
x-request-id: "1f383679-c613-4717-ac1c-72adc9720021"
x-runtime: "0.329230"
server: "WEBrick/1.3.1 (Ruby/2.1.2/2014-05-08)"
date: "Tue, 24 Mar 2015 00:39:39 GMT"
content-length: "7"
connection: "close"
set-cookie: "request_method=POST; path=/"
----------------------------------------------
I, [2015-03-23T17:39:39.938169 #8274]  INFO -- : post http://localhost:3000/
D, [2015-03-23T17:39:39.938230 #8274] DEBUG -- request: User-Agent: "Faraday v0.9.1"
I, [2015-03-23T17:39:39.942782 #8274]  INFO -- Status: 400
D, [2015-03-23T17:39:39.942874 #8274] DEBUG -- response: server: "WEBrick/1.3.1 (Ruby/2.1.2/2014-05-08)"
date: "Tue, 24 Mar 2015 00:39:39 GMT"
content-length: "0"
connection: "close"
```

And for the Rails Server (notice how the second request doesn't show up here):
```
$ bin/rails server
=> Booting WEBrick
=> Rails 4.2.1 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
[2015-03-23 17:39:24] INFO  WEBrick 1.3.1
[2015-03-23 17:39:24] INFO  ruby 2.1.2 (2014-05-08) [x86_64-darwin13.0]
[2015-03-23 17:39:24] INFO  WEBrick::HTTPServer#start: pid=8154 port=3000


Started POST "/" for ::1 at 2015-03-23 17:39:39 -0700
Processing by ApplicationController#hello_world as */*
  Parameters: {"From: \"Me\" <info@info.com>\nTo: \"You\" <info@info.com>\nHello"=>nil}
  Rendered text template (0.0ms)
Completed 200 OK in 20ms (Views: 8.8ms | ActiveRecord: 0.0ms)
```

**Comment by tpitale** [comment]
That's awesome @tbreier thanks! Can you try using `c.request :url_encoded` in your Faraday setup in your test. If that works I'll add it to mail_room. If not, I'll pull everything down and see if I can investigate.

**Comment by tbreier** [comment]
Of course!
I added `c.request :url_encoded` but it didn't seem to have an effect, unfortunately.
I also added `URI.encode_www_form_component(message)` as a third request, and this works. But not sure if that's the right way to go about this.

**Comment by tpitale** [comment]
Yeah, I'm not sure why Rails is failing on this … and until we get a better idea of what's going wrong I hesitate to make an encoding change. So strange! Thanks again for all your investigation on this. I will definitely check it out asap.

**Comment by tpitale** [comment]
Oh wait, I did that test on released gems 1.2.0 of DM. Let me try with masters.

**Comment by buchgr** [comment]
Thanks @tbreier . Having similar issues but couldn't nail it down exactly. That app of yours is awesome!

**Comment by tbreier** [comment]
I agree not to rush things, encoding stuff can be tricky and/or lead to unexpected behavior. Curious what you'll find out while investigating!
Oh and thank you again for this gem and for responding so fast! :smile:

**Comment by tbreier** [comment]
DM?

**Comment by tpitale** [comment]
Sorry, working on a datamapper issue and got my tabs confused.
