### ISSUE TITLE
StartTLS support

### ISSUE THREAD

**Issue by Javex** [tpitale/mail_room#41]
I'm not a ruby guy so I can't implement this myself (but it seems the change would be primitive). My mail server only supports StartTLS (it doesn't acceppt non-encrypted connections and 993 is closed). So to connect to it, the `STARTTLS` upgrade needs to be performed.

From what I gather, `Net::IMAP#starttls` is a simple command to execute after connecting so it would be cool to have an option to trigger this once the connection is established.

**Comment by tpitale** [comment]
Hi @Javex, this is a gem (mostly) explicitly for gmail, due to certain gmail-specific behaviors and extensions that google added. I cannot guarantee that this will behave with your mail server in any way.

That being said, if someone wants to implement this as a PR, I'll certainly consider merging it … but, you may just find that mail_room misbehaves in other ways with your mail server.

**Comment by DouweM** [comment]
@tpitale With this gem now being used in GitLab, we obviously want it to work with any IMAP server, including those using StartTLS :) We have it working with a postfix server (which we also recommend on-premise users use), and haven't seen any strange behavior around Gmail extensions.

I've filed an issue in the GitLab CE issue tracker to add StartTLS support for Reply by email, and following from that, mail_room: https://gitlab.com/gitlab-org/gitlab-ce/issues/2711

**Comment by tpitale** [comment]
I just have no real way of testing all the different behaviors of other IMAP servers with any consistency. Saying "any" IMAP server gives me a bit of a chill. Glad it works with postfix.

As I said, happy to consider a PR. I might even do it myself if I have time. I'm not saying it shouldn't or can't work with other IMAP servers, I just don't know what sort of guarantee I can offer. I suppose I can just rely on people complaining if we break something :smile:

**Comment by tpitale** [comment]
Oh, and it looks like the gmail extension I was using (or maybe thinking of using) isn't in the code anymore. I either never finished that work, or deleted it. So, yeah, no reason it shouldn't generally work with IMAP.

**Comment by DouweM** [comment]
@tpitale IMAP is a standard, so we should be able to support anything that adheres to it :)

**Comment by tpitale** [comment]
Yeah. Gmail doesn't. That's why I hesitate. :smile:

**Comment by DouweM** [comment]
@tpitale Lol, fair enough. But I think the subset of IMAP that we use is small enough that it shouldn't be an issue. We already know that we support both Gmail and "regular IMAP" in the form of postfix as it is.

Adding StartTLS support shouldn't affect either :P

**Comment by tpitale** [comment]
Agreed.

So, back to StartTLS … does anyone know when this should be called? Before login, after login, :shrugs:? The docs aren't exactly clear: http://ruby-doc.org/stdlib-2.0.0/libdoc/net/imap/rdoc/Net/IMAP.html#method-i-starttls

**Comment by tpitale** [comment]
@Javex do you have a need to support any of the options for starttls (like, disabling verification)?

**Comment by tpitale** [comment]
This IMAP code is just another example of the truly weird in Ruby's stdlib.

**Comment by DouweM** [comment]
@tpitale Before login, for sure. The point is that we start unprotected, and then upgrade to TLS, and _then_ do all of the interesting stuff.
