### ISSUE TITLE
Handle encoding issues from email in JSON-using delivery methods

### ISSUE THREAD

**Issue by tpitale** [tpitale/mail_room#44]
Both `Que` and `Sidekiq` dump to json. Encodings other than properly recognized UTF-8 will trip json up.

From @DouweM:
A reproduction of the specific case GitLab users were having trouble with is this:

``` ruby
message = "é"
message.force_encoding("ASCII-8BIT")
```

Note that in this case, the message was actually UTF-8-encoded, but for some reason Ruby thought it was ASCII-8BIT, and when trying to do `JSON.generate`, it tried to convert this string that was actually UTF-8 encoded from ASCII-8BIT to UTF-8, yielding the `"\xC3" from ASCII-8BIT to UTF-8 (Encoding::UndefinedConversionError)` error you see in https://gitlab.com/gitlab-org/gitlab-ce/issues/2698.

Reproduce this by doing:

``` ruby
JSON.generate(message) # => error
```

In this case, simply doing `message.force_encoding('UTF-8')` would work, but not in this case, where the original message was ISO-8859-1 rather than UTF-8:

``` ruby
message = "é".encode('ISO-8859-1')
message.force_encoding('ASCII-8BIT')
message.force_encoding("UTF-8")
JSON.generate(message) # => error
```

**Comment by tpitale** [comment]
Relevant to my efforts: http://graysoftinc.com/character-encodings/ruby-19s-string

**Comment by tpitale** [comment]
The problem appears to be that ruby simply thinks the message is some encoding that it isn't (could be the version of ruby, or the system encoding, entirely unkown). If we could detect with ruby what the actual encoding was, as suggested in the gitlab issue, we could then `force_encoding` and `encode` to UTF-8. That seems to work reliably.

Now to find a better way for ruby to actually detect the encoding. `message.valid_encoding?` actually tells us that there is a mismatch between the characters in the string and the marked encoding. `message.scrub` will remove invalid characters for the encoding. None of this tells us how or why ruby doesn't detect the right encoding.

If we `force_encoding` to the proper encoding, `JSON.dump` properly converts the characters to UTF-8 encoding.

Here's one pure-ruby gem that does it: https://github.com/jmhodges/rchardet Code originally from Mozilla.

**Comment by tpitale** [comment]
Maybe there's a reliable way to get the encoding from the mail headers?

`Content-Type: text/html; charset="UTF-8"`

**Comment by DouweM** [comment]
@tpitale 

> Maybe there's a reliable way to get the encoding from the mail headers?
> 
> Content-Type: text/html; charset="UTF-8"

Parsing the mail message from within mail_room to get the headers out feels very wrong to me.

**Comment by tpitale** [comment]
I would agree. Just talking "out loud". :simple_smile:

**Comment by tpitale** [comment]
Our use of `charlock_holmes` seems to resolve this. May make it optional.
