### ISSUE TITLE
Address issues of raised errors on delivery crashing all of mail_room

### ISSUE THREAD

**Issue by tpitale** [tpitale/mail_room#45]
MailRoom should not crash when a message or delivery raises an error. The mailbox watcher should be properly supervised such that it simply restarts on that mailbox. Let it fail, and make a new watcher.

**Comment by Senorsen** [comment]
+1'd for this, hope it can be fixed soon

**Comment by tpitale** [comment]
Have you actually seen this issue? I wrote it as a completely hypothetical scenario.

**Comment by Senorsen** [comment]
@tpitale Yes, I have kept mail_room service running for days. One day a network issue occurred on this machine, after that, I noticed that mail_room service crashed. 
P.S. I was using the latest mail_room in GitLab.
See: https://github.com/gitlabhq/gitlabhq/issues/9712

And:
```
/usr/local/lib/ruby/2.1.0/net/imap.rb:1045:in `initialize': Network is unreachable - connect(2) for "imap.gmail.com" port 993 (Errno::ENETUNREACH)
        from /usr/local/lib/ruby/2.1.0/net/imap.rb:1045:in `open'
        from /usr/local/lib/ruby/2.1.0/net/imap.rb:1045:in `initialize'
        from /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/mail_room-0.6.1/lib/mail_room/mailbox_watcher.rb:20:in `new'
        from /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/mail_room-0.6.1/lib/mail_room/mailbox_watcher.rb:20:in `imap'
        from /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/mail_room-0.6.1/lib/mail_room/mailbox_watcher.rb:88:in `log_in'
        from /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/mail_room-0.6.1/lib/mail_room/mailbox_watcher.rb:69:in `setup'
        from /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/mail_room-0.6.1/lib/mail_room/mailbox_watcher.rb:149:in `rescue in block in run'
        from /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/mail_room-0.6.1/lib/mail_room/mailbox_watcher.rb:141:in `block in run'

```
# ps -ef | grep mail
## (No process in the result)
```

**Comment by tpitale** [comment]
I would suggest in your case to use a process monitor like init or upstart.

**Comment by tpitale** [comment]
The readme suggests https://github.com/tpitale/mail_room/wiki/Init-Scripts-for-Running-mail_room

**Comment by tpitale** [comment]
Let's open a new issue to rescue `Errno::ENETUNREACH` cases. Mind opening that @Senorsen.
