### ISSUE TITLE
Having N mail_rooms on N application servers will result in 1 message being processed N times

### ISSUE THREAD

**Issue by DouweM** [tpitale/mail_room#46]
In the case of GitLab, this means every "Reply by email" message would result in N comments being created.

See https://gitlab.com/gitlab-org/gitlab-ce/issues/2870.

@tpitale What's your take on this? Our (@jacobvosmaer and me) solution has mail_room use Redis to keep track of what messages have been processed, so that only one mail_room ever processes a specific message, but this does add complexity to mail_room that a lot of use cases (like yours, it appears) don't need.

**Comment by tpitale** [comment]
I think we should pass the message id from the IMAP server. Then the receiving application can choose to process a message or not.

Trying to introduce a syncing system to mail room will most likely be a nightmare. And will probably just result in race conditions we may not be able to solve because they are environment specific.

**Comment by tpitale** [comment]
Better yet, (at least with gmail) there is a message-id header:

`Message-ID: <CAKCQogc=V8w_LuBOoXAeDz8X4q-yqdwxP+8PRM9P0SxH22FRTg@mail.gmail.com>`

If using the mail gem and `Mail.read_from_string`, the object has the `message_id`:

```ruby
m = Mail.read_from_string(message)
puts m.message_id #=> "CAKCQogc=V8w_LuBOoXAeDz8X4q-yqdwxP+8PRM9P0SxH22FRTg@mail.gmail.com"
```

**Comment by tpitale** [comment]
Just read over the gitlab issue. I'm still not sure I agree that making mail_room into a distributed system is a good idea. It's certainly more than what I intended.

I'm curious why gitlab isn't just running 1 instance of mail_room? I probably don't understand much about how gitlab is deployed/scaled. But, I presume a share-nothing architecture is more ideal for someone running 48 instances.

**Comment by tpitale** [comment]
Again, just thinking out loud.

**Comment by DouweM** [comment]
@tpitale:

> I think we should pass the message id from the IMAP server. Then the receiving application can choose to process a message or not.

This would still leave us with 48 Sidekiq jobs for every single incoming email. This is definitely cleaner, but we would prefer to catch these "duplicates" as early in the process as possible.

> If using the mail gem, Mail.read_from_string, the object has the message_id:

I'd refrain from parsing emails in mail_room, and we can't be 100% sure that message IDs are unique, but we could definitely use a hash of the raw message source to function as the unique message ID.

> I'm still not sure I agree that making mail_room into a distributed system is a good idea. It's certainly more than what I intended.

Hence my hesitation to add this to mail_room. If we want to add complex stuff like this, it may be better to just make a proper fork of mail_room.

> I'm curious why gitlab isn't just running 1 instance of mail_room?

The 48 instances all run the same GitLab package, but use a centralized Postgres, Redis etc. The GitLab package has Rails, Sidekiq and MailRoom services/processes. Running mail_room on just one of these identical instances isn't an option, and we _want_ to be able to scale mail_room along with these other processes.

**Comment by tpitale** [comment]
> I'd refrain from parsing emails in mail_room …

Sorry, wasn't suggesting that, was just thinking about how easy it is to get message id for the receiving application. This was _before_ I had read the gitlab issue.

**Comment by DouweM** [comment]
@tpitale Ah, right.

**Comment by tpitale** [comment]
@DouweM can you tell me more about the way reply-to emails work? How easy/hard is it to create N reply-to email addresses/inboxes? Or, some other method of semi-randomly distributing emails to distinct inboxes, say 1 inbox for each instance of gitlab.

Based on your comment about scaling, that's the best way I can think of. Then, each mail_room instance would only listen to one, non-overlapping, inbox.

Alternatively, this could be accomplished with labels or some other mechanism (depending on the mail server used). Then, each mail_room instance could be configured to search for different labels.

**Comment by tpitale** [comment]
From a user perspective, they have to hit _reply_ anyway, so it's not as if they're typing in the email address. Seems like automatically generated email accounts shouldn't be much of a problem there.

**Comment by DouweM** [comment]
@tpitale We can't know if the specific setup GitLab runs in allows differences in configuration between instances (i.e. what inbox is read from). Even if it does, the number of GitLab instances should be allowed to be scaled up/down freely, without emails ending up nowhere when the GitLab instances in question is removed. The assumption is that every GitLab instance is identical, and so is the mail_room configuration.

**Comment by tpitale** [comment]
Ouch.

**Comment by DouweM** [comment]
@tpitale Yep :(

**Comment by tpitale** [comment]
I mean … in that case, mail_room isn't going to scale. It's just, sharing an inbox.

**Comment by tpitale** [comment]
If the instances of postgres/redis/etc are a shared instance. Could mail_room be moved to that?

**Comment by DouweM** [comment]
@tpitale A server dedicated to running mail_room that has to manage all incoming messages definitely isn't going to scale. At least with one mail_room per GitLab instance, 48 different message can be processed concurrently by 48 different mail_rooms.

If the mailserver is sufficiently performant, like we can expect Gmail to be, all mail_rooms using the same inbox shouldn't be a problem, should it?

**Comment by DouweM** [comment]
@tpitale It's also harder to get High Availability customers to run a separate machine for just processing reply by email, than it is Postgres/Redis.

**Comment by tpitale** [comment]
Yeah. Just spitballing.

**Comment by DouweM** [comment]
@tpitale I know :)

**Comment by tpitale** [comment]
I guess my point about scaling is that you're going to basically have a single lock/mutex. And there are a ton of issues that will arise from adding that complexity. And doing so in mail_room is basically tying us to the particulars of gitlab's implementation.

For other environments, if I needed to scale, I would probably do one of the things mentioned above.

**Comment by tpitale** [comment]
I was trying to think of a way to mark the messages in the mailbox using a label as a "lock". But there's no way to guarantee contention and unlocking, etc etc etc.

**Comment by DouweM** [comment]
@tpitale A lock _for a specific message_, only checked the moment mail_room want to start processing it; different messages will still be processed concurrently by different mail_rooms so the lock shouldn't affect performance too much, and while it's definitely complex, I can't think of any issues this would create.

**Comment by DouweM** [comment]
@tpitale IMAP may be atomic, but there is no "compare and swap" or anything, so two mail_rooms can't know if they were the one that set the label, if it was already there, or added between there `has_label?` and `set_label` calls.

**Comment by tpitale** [comment]
Just an example: What happens if the message is failed to process … the lock may get removed, but the message has probably been passed-over by the other mail_rooms.

**Comment by DouweM** [comment]
@tpitale Failed to process how? MailRoom doesn't do anything interesting, so should "always" succeed in pushing it to Sidekiq.

**Comment by DouweM** [comment]
@tpitale Anyway, I'm going into a call. Let's continue this discussion later.

**Comment by tpitale** [comment]
@DouweM maybe we should hop on a call later today. :smile: 

I'd definitely consider merging something, as long as it wasn't _required_ (as you could probably guess), and it worked on all delivery methods. It would be nice if the mechanism was abstracted so we could later add other mechanisms like using postgresql advisory locks or something like that.

Let me know if you want to do a call, or just spike something out.

**Comment by tpitale** [comment]
Even better, if it didn't even fetch messages that were already being worked on by other instances. Maybe something inside here: https://github.com/tpitale/mail_room/blob/master/lib/mail_room/mailbox_handler.rb#L47-L49

That would greatly reduce the work each instance is doing. Most of what mail_room spends its time is in fetch and delivery.

**Comment by tpitale** [comment]
@DouweM Sorry I missed the call. I was on standup of my own. Why don't you go ahead with your plan, and let's see how complex it becomes.

**Comment by DouweM** [comment]
@tpitale I will :)

**Comment by tpitale** [comment]
Thanks!
