### ISSUE TITLE
Add arbitration to readme

### ISSUE THREAD

**Issue by tpitale** [tpitale/mail_room#50]
* scenarios for arbitration
* no guarantee of non-duplicates, just our best effort to reduce
* pre-reqs, aka redis at this time
* advice for handling dups, in case (idempotent)

**Comment by DouweM** [comment]
Why can't we give that guarantee?

**Comment by tpitale** [comment]
Covering our bases for the unexpected. Maybe that'll change after gitlab has run arbitration for some time. But, my guess is that we've missed something, as is always the case in distributed systems.

It's mostly as a word of caution, that no system is perfect. E.g., what happens in different failure scenarios (redis goes down, is slow, or simply loses data).

**Comment by tpitale** [comment]
@DouweM I stubbed out the README changes. Would you mind filling in the configuration. Go ahead and push right to master.

**Comment by DouweM** [comment]
@tpitale Done.
