### ISSUE TITLE
Redis sentinel support

### ISSUE THREAD

**Issue by brodock** [tpitale/mail_room#55]
Could you include support for defining a sentinel-enabled connection?
redis-rb already support so, all you have to do is pass "sentinels" array of hashes connection param.

Ideally you would change "redis_url" YAML key to just "redis" and accept every redis possible setting:
* url
* host
* port
* password
* db
* namespace
* sentinels

See: https://github.com/redis/redis-rb#sentinel-support

**Comment by tpitale** [comment]
Will certainly look into it.

**Comment by brodock** [comment]
please, ping me if you need any help.

**Comment by tpitale** [comment]
PRs certainly welcome!

**Comment by tpitale** [comment]
@brodock Is this something you still need? PRs welcome.

I don't personally use redis, so I'm going to close this for now.

**Comment by brodock** [comment]
@tpitale I will need that. We are working into getting Redis Sentinel working with GitLab and its dependencies so me or someone from the Team will make a PR soon :-)

If you are curious about, see: https://gitlab.com/gitlab-org/gitlab-ee/issues/77

**Comment by tpitale** [comment]
The changes can be made in

* https://github.com/tpitale/mail_room/blob/master/lib/mail_room/arbitration/redis.rb#L6-L13
* https://github.com/tpitale/mail_room/blob/master/lib/mail_room/delivery/sidekiq.rb#L11-L20

I'd like to, if possible, keep the existing keys working for the time being.

**Comment by brodock** [comment]
@tpitale I've sent a PR for the sentinel support: #79
Sentinel can be a lot trickier to get right (I've tried to summarize the important parts in the Pull Request) but if you have any issue or want to dig deeper, please check this documentation I'm working on: https://gitlab.com/gitlab-org/gitlab-ce/blob/1f3d8962dbc3429b19a8dea3375dcc4cc3b12f70/doc/administration/high_availability/redis.md#redis-sentinel-support

Feel free to ping me anytime.
