### ISSUE TITLE
Add debug mode to diagnose issues

### ISSUE THREAD

**Issue by stanhu** [tpitale/mail_room#65]
It would be really helpful to have a debug mode that shows what mail_room is doing so that we can diagnose whether there is an issue with the configuration, mail_room, or the IMAP server. It can just be a configuration flag (e.g. `-d` or `-v`).

/cc: @godfat

**Comment by DouweM** [comment]
@ZJvandeWeg's fork has more logging: https://github.com/ZJvandeWeg/mail_room/tree/logger

**Comment by ZJvandeWeg** [comment]
@DouweM Forgot about that, Ill create a PR on this project. 😄

**Comment by tpitale** [comment]
@stanhu Can you document specifically what you'd like to see in debugging information? If there is an issue with configuration, we should be failing/erroring in some way. Same goes for the IMAP server itself.

Printing out information may be helpful, but I'm curious to know more about what you're hoping to accomplish.

**Comment by stanhu** [comment]
@tpitale I think @ZJvandeWeg has a good start there in his branch. Here's what would be helpful from my perspective:

* Trace debugging mode where an admin can see the entire IMAP command/response flow (perhaps scrubbing passwords if necessary) 
* Print out configuration at startup (e.g. we noticed a mailbox name was `nil` but mail_room didn't fail in an obvious way)

@godfat, any other things that you found helpful?

**Comment by godfat** [comment]
@stanhu Yes, any exceptions should be logged, along with backtrace (`take(10)` should be good enough, like in my [testing branch](https://github.com/godfat/mail_room/pull/1/files#diff-87cfbf97fe8ebfa9cf580526abfc9908R183)). For now errors are silently swallowed, which makes it very hard to debug.

**Comment by tpitale** [comment]
Aside from a 2 specific errors, mail_room is designed to crash on error (let it fail). The error and backtrace are logged to stdout/err and logged by your process manager of choice.

We fix errors as reported.

I'm not sure where you're seeing all errors being swallowed.

**Comment by godfat** [comment]
To be specific, this one:
https://github.com/tpitale/mail_room/blob/v0.7.0/lib/mail_room/mailbox_watcher.rb#L135

**Comment by tpitale** [comment]
@stanhu there should be an error for something specific like a mailbox `name` being nil. MailRoom crashes if you try to imap `select` a `nil`. But we can be more helpful as to the specific misconfiguration. I've opened issue #71.

**Comment by godfat** [comment]
More reasoning:

We won't want to crash upon disconnection, and if it's not logged, we won't ever realize that Handler was not using the same imap connection as Watcher. I needs to be logged to debug this issue.

**Comment by tpitale** [comment]
@godfat That's 2 specific errors. IOError and Net::IMAP errors (including subclasses). That's not all errors.

**Comment by godfat** [comment]
@tpitale They're called errors and they're exceptions, and without them being logged we cannot diagnose issues. With the introduction of loggers, we could log them with WARN or INFO, that's fine. As long as there's a way to log them.

**Comment by tpitale** [comment]
@godfat: they are being logged when the process crashes. By design.

**Comment by tpitale** [comment]
I'm going to run some tests. But <OpenSSL::SSL::SSLError: SSL_write: bad write retry> that you saw would have crashed the process as evidenced by the constant respawning by the process manager as mentioned in #61. That error is not a subclass of either of the errors we rescue. 

```ruby
[OpenSSL::SSL::SSLError, OpenSSL::OpenSSLError, StandardError, Exception, Object, Kernel, BasicObject]
```

Where does your process manager log STDOUT and STDERR to?

**Comment by tpitale** [comment]
I'm very tempted to go back to letting ALL errors crash mail_room like I had originally designed it to do.

**Comment by godfat** [comment]
@tpitale Process isn't crashing because they're rescued. I guess we're probably not on the same page, I am not sure which you're referring to?

**Comment by tpitale** [comment]
Only 2 errors are rescued. The rest are NOT rescued.

**Comment by tpitale** [comment]
It's not `rescue => e` which is ALL errors/exceptions. It's not just `rescue`.

**Comment by tpitale** [comment]
If the process wasn't crashing … why was it respawning as per #61?

**Comment by godfat** [comment]
I was talking about the rescued ones, i.e. IOError and Net::IMAP.

Respawning? Are you referring to: https://github.com/tpitale/mail_room/issues/61#issuecomment-218639890
I was not talking about that, and I think @gdmalet was seeing another issue. I am fine for crashing the process for not expected errors, since we need to fix them anyway.

**Comment by tpitale** [comment]
@godfat Those are rescued for a reason. See #15 and @DouweM commit on https://github.com/tpitale/mail_room/commit/73ddcf7f. Also See #11 & #12 for reasoning behind reconnecting on IMAP disconnect.

**Comment by tpitale** [comment]
Previously those disconnects were happening silently, because the idling thread was not aborting on exception. Now that we do that, we can remove the Net::IMAP rescue.

**Comment by tpitale** [comment]
But, that will crash ALL mailboxes for simple disconnects.

Maybe instead of the Net::IMAP::Error superclass, we can look for a specific kind of disconnect (like BYE) only.

**Comment by tpitale** [comment]
Nope, we have to rescue `Net::IMAP::Error` because that's what disconnecting in `idle` raises: https://github.com/ruby/ruby/blob/trunk/lib/net/imap.rb#L962 It sucks that that's the superclass for other kinds of errors.

But, we can check for that in the rescue … and re-raise if it's a subclass but not Error itself, maybe.

**Comment by godfat** [comment]
@tpitale I am not familiar with IMAP enough to say which exceptions we shouldn't rescue, so I am totally ok to rescue all `Net::IMAP::Error`, but indeed we probably shouldn't rescue exceptions for saying that some IMAP commands were not implemented. Actually, I am more leaning toward to rescue all `Net::IMAP::Error` because we need a robust process which could recover itself.

At any rate, they should still be logged in order to diagnose issues. For example, some IMAP server might not be working properly, we need information from the clients.

**Comment by tpitale** [comment]
I'll say it again @godfat: mail_room is designed to crash. If it errors, we want to let it fail. The robustness is handled by tools that are intentionally designed for that. "Recovery" is not in the plan.

**Comment by tpitale** [comment]
If mail_room crashes THEY ARE LOGGED.

**Comment by tpitale** [comment]
I'm sorry, but I'm not going to continue talking in circles. I appreciate all the conversation, but I don't believe this is actually a problem in MailRoom.

I'm going to try to:

1. reduce the scope of errors that are rescued to ONLY cover disconnects during idle
2. Rollback IOError to simple EOFError, and check for specific cases

All other errors will, at this time, crash mail_room process, where the error will be on STDOUT or STDERR and available to be logged by a process manager.

Thank you again.

**Comment by tpitale** [comment]
I'll be opening a new PR with my refactoring to watcher and handler. This should further limit the scope of the rescue to ONLY the idle command. Allowing other errors (during fetching of messages) to crash mail_room.

**Comment by tpitale** [comment]
Specific proof of mail_room crashing for misconfiguration:

```
ruby -Ilib bin/mail_room -c ~/.mail_room.yml
/Users/tpitale/.rubies/ruby-2.2.2/lib/ruby/2.2.0/net/imap.rb:1171:in `get_tagged_response':  Unknown Mailbox: NIL (Failure) (Net::IMAP::NoResponseError)
	from /Users/tpitale/.rubies/ruby-2.2.2/lib/ruby/2.2.0/net/imap.rb:1225:in `block in send_command'
	from /Users/tpitale/.rubies/ruby-2.2.2/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
	from /Users/tpitale/.rubies/ruby-2.2.2/lib/ruby/2.2.0/net/imap.rb:1207:in `send_command'
	from /Users/tpitale/.rubies/ruby-2.2.2/lib/ruby/2.2.0/net/imap.rb:453:in `block in select'
	from /Users/tpitale/.rubies/ruby-2.2.2/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
	from /Users/tpitale/.rubies/ruby-2.2.2/lib/ruby/2.2.0/net/imap.rb:451:in `select'
	from /Users/tpitale/Development/Personal/OSS/mail_room/lib/mail_room/mailbox_watcher.rb:95:in `set_mailbox'
	from /Users/tpitale/Development/Personal/OSS/mail_room/lib/mail_room/mailbox_watcher.rb:70:in `setup'
	from /Users/tpitale/Development/Personal/OSS/mail_room/lib/mail_room/mailbox_watcher.rb:121:in `run'
	from /Users/tpitale/Development/Personal/OSS/mail_room/lib/mail_room/coordinator.rb:19:in `each'
	from /Users/tpitale/Development/Personal/OSS/mail_room/lib/mail_room/coordinator.rb:19:in `run'
	from /Users/tpitale/Development/Personal/OSS/mail_room/lib/mail_room/cli.rb:52:in `start'
	from bin/mail_room:5:in `<main>'
```
