### ISSUE TITLE
Structured logging of message fetching and delivery

### ISSUE THREAD

**Issue by tpitale** [tpitale/mail_room#76]
It may be valuable to know that messages are being fetched/processed/delivered to a remote location in a structured log. Still undecided on this. If using que/sidekiq new jobs will be processed; if using logger all messages are already logged. Only in a remote delivery case (callbacks) would it be especially hard to know if new messages were being fetched/delivered without a log if the remote service is not within the users control.

**Comment by tpitale** [comment]
This also makes me think about other instrumentation like timing and stats into influxdb or something.

With structured logs we could consume the log and send stats as a distinct process. Or ship the right off to log processing tools to be analyzed.

**Comment by cablett** [comment]
Hi @tpitale ! I started [a PR](https://github.com/tpitale/mail_room/pull/88) continuing @ZJvandeWeg 's [earlier work on structured logging](https://github.com/tpitale/mail_room/pull/66/files). What do you think?

**Comment by tpitale** [comment]
Resolved in #88.
