### ISSUE TITLE
Need to call expunge() or close() sometime to delete messages

### ISSUE THREAD

**Issue by craigmiskell-gitlab** [tpitale/mail_room#85]
I can't find anywhere that mail_room tells the IMAP server to actually delete messages flagged as DELETED; my understanding is that it would be by calling close() or expunge().  I can confirm that our gmail inbox has a large number (>200K) messages, nearly all marked DELETED but never actually expunged.

Am I missing something?

**Comment by tpitale** [comment]
I don't think you're missing anything. It was probably a lack of knowledge (or library documentation) on my part when it was initially added.

**Comment by tpitale** [comment]
PR welcome 😄

**Comment by craigmiskell-gitlab** [comment]
Will do :)

**Comment by tpitale** [comment]
@craigmiskell-gitlab Do you think `MailRoom` should be the one to expunge these? Maybe it should be a configuration setting (like we do with `delete_after_delivery`)?

Also, for my records, here is the docs for expunge: https://ruby-doc.com/stdlib/libdoc/net/imap/rdoc/Net/IMAP.html#method-i-expunge

**Comment by craigmiskell-gitlab** [comment]
Sorry I hadn't come back to this since June, I have been prioritising other work.   

Yes, I think MailRoom should be the one to do this; enabling by configuration is fine, but it's the best placed to be sure of doing it at the right time.

**Comment by tpitale** [comment]
Thanks. I'll try to knock this out. I think I know how/where to do it.
